;==========================================================
;              POLYBAR — DARK FLOATING STYLE
;==========================================================

[colors]

background     = #1a202b
background-alt = #161B24

foreground          = #D8DEE9
foreground-white    = #FFFFFF
foreground-dim      = #6F7785

pink                = #F5C2E7
blue                = #89B4FA
green               = #A6E3A1
yellow              = #F9E2AF
purple              = #CBA6F7
orange              = #FAB387
red                 = #F38BA8

workspace-active    = #FFFFFF
workspace-underline = #89B4FA
workspace-1 = #F38BA8
workspace-2 = #F9E2AF
workspace-3 = #A6E3A1
workspace-4 = #89B4FA
workspace-5 = #CBA6F7
workspace-6 = #FAB387
workspace-7 = #89DCEB
workspace-8 = #F5C2E7
workspace-9 = #94E2D5
workspace-10 = #EBA0AC

alert               = #BF616A
disabled            = #4C566A


;==========================================================
; SETTINGS
;==========================================================

[settings]

screenchange-reload = true
pseudo-transparency = false


;==========================================================
; BAR
;==========================================================

[bar/example]

;==========================================================
; MONITOR
;==========================================================

monitor = HDMI-A-0
monitor-strict = true

;==========================================================
; POSITION
;==========================================================

width = 97%
height = 32

offset-x = 1.5%
offset-y = 4

bottom = false
fixed-center = true

;==========================================================
; WINDOW MANAGEMENT
;==========================================================

override-redirect = true
wm-restack = i3
enable-struts = true

;==========================================================
; APPEARANCE
;==========================================================

radius = 5

background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 0
padding-right = 0

border-size = 0
border-color = ${colors.background}

module-margin-left = 0
module-margin-right = 0

separator =

line-size = 3pt


;==========================================================
; FONTS
;==========================================================

font-0 = "AdwaitaMono Nerd Font:style=Bold:size=12;3"
font-1 = "AdwaitaMono Nerd Font:size=15;2"
font-2 = "Symbols Nerd Font Mono:size=16;2"
font-3 = "Symbols Nerd Font Mono:size=12;2"


;==========================================================
; MODULES
;==========================================================

modules-left = arch xworkspaces tray xwindow
modules-center = i3-mode
modules-right = pulseaudio wlan memory redshift xkeyboard date

cursor-click = pointer
cursor-scroll = pointer

enable-ipc = true


;==========================================================
; ARCH LINUX
;==========================================================

[module/arch]

type = custom/text

format = %{O14}%{O16}

format-font = 2
format-foreground = ${colors.blue}
format-background = ${colors.background}

click-left = rofi -show drun


;==========================================================
; WORKSPACES
;==========================================================

[module/xworkspaces]

type = internal/xworkspaces

format = <label-state>

icon-0 = 1;%{F#F38BA8}1%{F-}
icon-1 = 2;%{F#F9E2AF}2%{F-}
icon-2 = 3;%{F#A6E3A1}3%{F-}
icon-3 = 4;%{F#89B4FA}4%{F-}
icon-4 = 5;%{F#CBA6F7}5%{F-}
icon-5 = 6;%{F#FAB387}6%{F-}
icon-6 = 7;%{F#89DCEB}7%{F-}
icon-7 = 8;%{F#F5C2E7}8%{F-}
icon-8 = 9;%{F#94E2D5}9%{F-}
icon-9 = 10;%{F#EBA0AC}10%{F-}

index-sort = true
wrapping-scroll = false

;----------------------------------------------------------
; CURRENT WORKSPACE
;----------------------------------------------------------

label-active = %icon%
label-active-background = ${colors.background}
label-active-underline = ${colors.workspace-underline}
label-active-padding = 1

;----------------------------------------------------------
; OCCUPIED WORKSPACE
;----------------------------------------------------------

label-occupied = %icon%
label-occupied-background = ${colors.background}
label-occupied-padding = 1

;----------------------------------------------------------
; VISIBLE WORKSPACE
;----------------------------------------------------------

label-visible = %icon%
label-visible-background = ${colors.background}
label-visible-padding = 1

;----------------------------------------------------------
; URGENT WORKSPACE
;----------------------------------------------------------

label-urgent = %icon%
label-urgent-background = ${colors.background}
label-urgent-underline = ${colors.red}
label-urgent-padding = 1

label-empty = %icon%
label-empty-padding = 1


;==========================================================
; SYSTEM TRAY
;==========================================================

[module/tray]

type = internal/tray

format = <tray>

tray-spacing = 5px
tray-size = 16px

tray-background = ${colors.background}
tray-foreground = ${colors.foreground}


;==========================================================
; WINDOW TITLE
;==========================================================

[module/xwindow]

type = internal/xwindow

format = <label>

format-background = ${colors.background}
format-padding = 1

label = %title%
label-foreground = ${colors.foreground}
label-maxlen = 50

label-empty = Desktop
label-empty-foreground = ${colors.foreground-dim}

;==========================================================
; I3 BINDING MODE
;==========================================================

[module/i3-mode]

type = custom/script
exec = ~/.config/polybar/i3-mode.sh
interval = 1

format = <label>
label = %output%
label-foreground = ${colors.orange}


;==========================================================
; VOLUME
;==========================================================

[module/pulseaudio]

type = internal/pulseaudio

use-ui-max = false

format-volume = <ramp-volume><label-volume>
format-volume-background = ${colors.background}
format-volume-padding = 0

format-muted = <label-muted>
format-muted-background = ${colors.background}
format-muted-padding = 1

label-volume = %percentage%%
label-volume-foreground = ${colors.orange}
label-volume-padding = 1

label-muted =    %percentage%%
label-muted-foreground = ${colors.foreground-dim}
label-muted-padding = 0

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = ${colors.orange}

click-left = pavucontrol
click-right = pavucontrol

scroll-up = #pulseaudio.inc
scroll-down = #pulseaudio.dec

;==========================================================
; WIFI
;==========================================================

[module/wlan]

type = custom/script
exec = ~/.config/polybar/wifi-status.sh
interval = 2
format = <label>
format-prefix = %{F#6F7785}%{F-}
format-background = ${colors.background}
format-padding = 1
label-foreground = ${colors.green}
click-right = nm-connection-editor


;==========================================================
; MEMORY
;==========================================================

[module/memory]

type = internal/memory

interval = 3

format = <label>
format-prefix = %{F#6F7785}%{F-}

format-background = ${colors.background}
format-padding = 1

label =  RAM %percentage_used%%
label-foreground = ${colors.purple}


;==========================================================
; REDSHIFT / NIGHT
;==========================================================

[module/redshift]

type = custom/text

format = 󱩌 NIGHT
format-prefix = %{F#6F7785}%{F-}

format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-padding = 1

click-left = redshift -O 4000
click-right = redshift -x
click-middle = redshift -O 3500


;==========================================================
; KEYBOARD LAYOUT
;==========================================================

[module/xkeyboard]

type = internal/xkeyboard

format = <label-layout>
format-prefix = %{F#6F7785}%{F-}
format-background = ${colors.background}
format-padding = 1

label-layout = %icon%
label-layout-foreground = ${colors.blue}

layout-icon-0 = us;EN
layout-icon-1 = ru;RU

;==========================================================
; DATE / TIME
;==========================================================

[module/date]

type = internal/date

interval = 1

date = %a %b %d
time = %H:%M:%S

format = <label>
format-prefix = %{F#6F7785}%{F-}

label = %date% %time%
label-foreground = ${colors.foreground}
label-padding = 1

;==========================================================
; END
;==========================================================
